import React from 'react';
import { Megaphone, Layers, BarChart2, Image, Link2 } from 'lucide-react';

const placeholders = [
  {
    icon: Link2,
    title: 'Meta Ads',
    description: 'Connect your Meta Business account to pull live ad performance — spend, ROAS, CPL, and campaign breakdowns.',
  },
  {
    icon: Image,
    title: 'Creatives',
    description: 'Browse and review ad creatives generated by the content engine. Filter by niche, format, and performance.',
  },
  {
    icon: BarChart2,
    title: 'Ad Stats',
    description: 'Track impressions, clicks, conversions, and cost per lead across all active campaigns in one view.',
  },
  {
    icon: Layers,
    title: 'Campaigns',
    description: 'Manage campaigns across niches. Pause, duplicate, or push new creatives directly from CortexaOS.',
  },
];

const Marketing: React.FC = () => {
  return (
    <div className="h-full flex flex-col p-6 overflow-y-auto" style={{ scrollbarWidth: 'none' }}>
      {/* Header */}
      <div className="flex items-center gap-3 mb-8">
        <div className="w-9 h-9 rounded-xl bg-[#A855F7]/15 flex items-center justify-center">
          <Megaphone size={17} className="text-[#A855F7]" />
        </div>
        <div>
          <h2 className="text-sm font-bold text-[#F2F2F2]">Marketing</h2>
          <p className="text-[11px] text-[#555]">Ad accounts, creatives, and campaign performance</p>
        </div>
      </div>

      {/* Coming soon banner */}
      <div className="bg-[#A855F7]/8 border border-[#A855F7]/20 rounded-xl px-5 py-4 mb-8 flex items-start gap-3">
        <div className="w-1.5 h-1.5 rounded-full bg-[#A855F7] mt-1.5 shrink-0" />
        <div>
          <p className="text-xs font-semibold text-[#A855F7] mb-0.5">Integrations coming soon</p>
          <p className="text-[11px] text-[#555] leading-relaxed">
            Meta Ads Manager, creative previews from the content engine, and live stat dashboards are all in progress.
            Connect your account once the integration is ready and this view populates automatically.
          </p>
        </div>
      </div>

      {/* Feature cards */}
      <div className="grid grid-cols-2 gap-4">
        {placeholders.map(({ icon: Icon, title, description }) => (
          <div key={title}
            className="bg-[#0F0F0F] border border-[#1E1E1E] rounded-xl p-5 flex flex-col gap-3 opacity-60">
            <div className="w-8 h-8 rounded-lg bg-[#1E1E1E] flex items-center justify-center">
              <Icon size={15} className="text-[#555]" />
            </div>
            <div>
              <p className="text-xs font-semibold text-[#909090] mb-1">{title}</p>
              <p className="text-[11px] text-[#383838] leading-relaxed">{description}</p>
            </div>
            <div className="mt-auto">
              <span className="inline-flex items-center px-2 py-0.5 rounded text-[9px] font-semibold uppercase tracking-wider bg-[#1E1E1E] text-[#383838]">
                Coming soon
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Marketing;
