import re, pathlib

template_path = pathlib.Path(r"C:/Users/Ayaan/Desktop/AIW2/Contractors/AIW2.0STACK-Landscaping/website-factory/templates/proposal/proposal-template.html")
output_path   = pathlib.Path(r"C:/Users/Ayaan/Desktop/AIW2/Contractors/AIW2.0STACK-Landscaping/website-factory/clients/_agency/demo-proposal.html")

html = template_path.read_text(encoding="utf-8")

logo_html = '<span style="font-weight:800;font-size:1.1rem;letter-spacing:-0.03em;color:#0A0A0F">Green Ridge<span style="color:#CD3D35">.</span></span>'

pyramid_html = '<div style="padding:2rem;background:#f1f5f9;border-radius:12px;text-align:center;color:#64748b;font-size:.9rem;margin:1rem 0">[SEO pyramid — generated by build-proposal.py from sitemap.json]</div>'

replacements = {
    "AGENCY_NAME": "Cortexa Labs",
    "AGENCY_DOMAIN": "cortexalabsai.com",
    "AGENCY_FOUNDER_FIRST_NAME": "Ayaan",
    "AGENCY_PRIMARY_CONTACT": "Ayaan Khan",
    "AGENCY_PORTRAIT_CAPTION": "Ayaan Khan, Founder of Cortexa Labs",
    "AGENCY_FOOTER_TAGLINE": "AI-powered websites for landscaping companies.",
    "AGENCY_FORMULA_OUTCOME": "More Estimate Calls Booked",
    "AGENCY_BLUEPRINT_NAME": "Cortexa Build Blueprint",
    "AGENCY_SOP_PASSWORD": "demo1234",
    "AGENCY_REVIEW_COUNT": "1",
    "AGENCY_VALUE_PROP_1_HTML": "<strong>2,000</strong> page views in 20 days for a home services client",
    "AGENCY_VALUE_PROP_2_HTML": "<strong>#1</strong> Google Maps ranking achieved in under 3 weeks",
    "AGENCY_VALUE_PROP_3_HTML": "<strong>3</strong> new jobs closed directly from the website in the first month",
    "AGENCY_PROMISE_HTML": "A landscaping website that ranks on Google, builds trust with homeowners, and books estimate calls &mdash; delivered in 5&ndash;7 days. <strong>One job from the site pays for it twice over.</strong>",
    "AGENCY_PROOF_STAT": "2,000+",
    "AGENCY_PROOF_STAT_SUBTITLE": " page views in 20 days",
    "AGENCY_PROOF_INTRO_PARAGRAPH": "Here is what a Cortexa Labs website did for a home services business in the first 20 days: 2,000 page views, a #1 Google Maps ranking, and 3 new jobs booked directly from the site. No ad spend. No cold calling.",
    "AGENCY_PROOF_VIDEO_URL": "https://youtube.com/@cortexalabs",
    "AGENCY_PROOF_VIDEO_THUMBNAIL_URL": "https://placehold.co/800x450/0A0A0F/CD3D35?text=Case+Study",
    "AGENCY_PROOF_VIDEO_TITLE": "How We Got a Home Services Client to #1 on Google Maps in 3 Weeks",
    "AGENCY_PROOF_VIDEO_CAPTION": "Watch the story",
    "AGENCY_REASON_TWO_TITLE": "Results in Weeks",
    "AGENCY_REASON_TWO_BODY": "A home services client hit 2,000 page views and a #1 Maps ranking in under 3 weeks. Your site is built the same way &mdash; local SEO baked in from day one.",
    "AGENCY_REASON_THREE_TITLE": "Risk-Free Build",
    "AGENCY_REASON_THREE_BODY": "You pay 50% upfront and 50% when you approve the finished site. Revisions included until you are happy.",
    "AGENCY_TRAFFIC_AUDIT_HEADING": "What we check on your current online presence",
    "AGENCY_SETUP_FEE_PRICE": "$1,200",
    "AGENCY_SETUP_FEE_STANDARD": "$1,500",
    "AGENCY_ONE_TIME_OFFER_PRICE": "$1,000",
    "AGENCY_MONTHLY_FEE_PRICE": "Included",
    "AGENCY_STACKED_VALUE_TOTAL": "$4,200",
    "AGENCY_VALUE_STACK_LINE_1_NAME": "Custom Landscaping Website Build",
    "AGENCY_VALUE_STACK_LINE_1_MSRP": "$1,800",
    "AGENCY_VALUE_STACK_LINE_2_NAME": "Local SEO Setup (service + location pages)",
    "AGENCY_VALUE_STACK_LINE_2_MSRP": "$800",
    "AGENCY_VALUE_STACK_LINE_3_NAME": "AI Lead Chatbot (Voiceflow)",
    "AGENCY_VALUE_STACK_LINE_3_MSRP": "$700",
    "AGENCY_VALUE_STACK_LINE_4_NAME": "Lead Automation (Make.com to inbox/CRM)",
    "AGENCY_VALUE_STACK_LINE_4_MSRP": "$500",
    "AGENCY_VALUE_STACK_LINE_5_NAME": "Google Reviews + Trust Badge Setup",
    "AGENCY_VALUE_STACK_LINE_5_MSRP": "$400",
    "ROI_DEFAULT_LEADS": "4",
    "ROI_DEFAULT_TICKET": "$10,000",
    "ROI_DEFAULT_TICKET_NUMERIC": "10000",
    "ROI_DEFAULT_LIFT": "$40,000/year",
    "COMPANY_NAME": "Green Ridge Landscaping",
    "COMPANY_BRAND": "Green Ridge",
    "COMPANY_DOMAIN": "greenridgelandscaping.com",
    "COMPANY_ADDRESS_DISPLAY": "4821 Oak Trail Blvd, Dallas, TX 75201",
    "COMPANY_LICENSE_DISPLAY": "TX-2024-8841",
    "COMPANY_LOGO_HTML": logo_html,
    "CLIENT_SLUG": "green-ridge-landscaping",
    "LIVE_PREVIEW_URL": "about:blank",
    "OWNER_FIRST_NAME": "Marcus",
    "OWNER_FULL_NAME": "Marcus Webb",
    "OWNER_PHONE": "(214) 555-0192",
    "YEARS_IN_BUSINESS": "12",
    "NICHE_NOUN": "landscaper",
    "NICHE_NOUN_TITLE": "Landscaping",
    "NICHE_END_CUSTOMER": "homeowner",
    "NICHE_END_CUSTOMER_PLURAL": "homeowners",
    "NICHE_END_CUSTOMER_TITLE_PLURAL": "Homeowners",
    "CITY_PRIMARY": "Dallas",
    "CITY_PRIMARY_SLUG": "dallas",
    "STATE_CODE": "TX",
    "REGION_FULL": "Dallas-Fort Worth",
    "CITY_COUNT": "8",
    "REVIEW_RATING": "4.9",
    "REVIEW_COUNT": "87",
    "PYRAMID_HTML": pyramid_html,
}

for key, val in replacements.items():
    html = html.replace("{{" + key + "}}", val)

# swap portrait src to placeholder
html = html.replace(
    'src="agency-assets/agency-intro.png"',
    'src="https://placehold.co/400x500/0A0A0F/ffffff?text=AK"'
)

remaining = set(re.findall(r'\{\{[A-Z0-9_]+\}\}', html))
if remaining:
    print("UNSUBSTITUTED:", remaining)

output_path.write_text(html, encoding="utf-8")
print(f"OK  {output_path}  ({len(html):,} bytes)")
